#!/usr/bin/env ash
#!/bin/bash
set -eu

o=${0##*/}

case $1 in --help)
	case $o in
		micro-diff)
			printf %s\\n "Usage: $o [..diff arguments] <file to diff>"
		;;
		micro-diff-?*)
			printf %s\\n \
				"Usage: $o [...args] <file path>" \
				" executes: ${o#"micro-diff-"} [...same args] ~/.config/micro/(<file path>)" \
			;
		;;
		*) exit 2;;
	esac
	exit
esac


unset i
case $# in
	0) echo required an argument; exit 1;;
	1) i=$1; shift;;
	2) i=$2; set -- "$1";; # most of the times -> expected from my `alias micro-diff='\micro-diff --color=auto'`
	*) . ~/B/__sourceable/pop_to_i.sh;;
esac
path=$i

PWDDRIVE=${PWD%%["${PATHSEP:-/}"]*}
unset diff_path
case $path in /*|"$PWDDRIVE"/*) diff_path=$path;; *) diff_path=$PWD/$path; esac # todo: path does not detects all drives such as [A-Za-z]:/* , but should it do it?


case $o in
	micro-diff)    exec diff               "$@" "$path" ~/.config/micro/backups/"${diff_path//[\/\:]/"%"}";;
	micro-diff-?*) exec "${o#micro-diff-}" "$@"         ~/.config/micro/backups/"${diff_path//[\/\:]/"%"}";;
esac
